import "./globals.css";
import LoaderWrapper from "@/components/LoaderWrapper";
import QueryProvider from "@/components/QueryClientProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <QueryProvider>
      <LoaderWrapper>{children}</LoaderWrapper>
    </QueryProvider>
    </body>
    </html>
  );
}
