import "./globals.css";
import LoaderWrapper from "@/components/shared/LoaderWrapper";
import QueryProvider from "@/components/shared/QueryClientProvider";
import Header from "@/components/layout/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <QueryProvider>
      <LoaderWrapper>
        <Header />
        <main className="lg:pt-[150px] pt-[120px]">
          {children}
        </main>
      </LoaderWrapper>
    </QueryProvider>
    </body>
    </html>
  );
}
